spring.application.name=forniture

# Desactiva la caché de Thymeleaf para ver cambios en HTML sin reiniciar el servidor
spring.thymeleaf.cache=false

# Desactiva la caché de archivos estáticos (CSS, JS, imágenes) para que se actualicen al refrescar
spring.web.resources.cache.period=0

# Desactiva el sistema de cacheo interno de recursos estáticos
spring.web.resources.chain.cache=false



#Conection to the DataBase
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

#Firebae Service
firebase.bucket.name=muebles-palmares-gera.firebasestorage.app
firebase.storage.path=MPG/Images
firebase.json.path=firebase
firebase.json.file=muebles-palmares-gera-firebase-adminsdk-fbsvc-d6ffd33ec8.json

server.port=${PORT:8080}
