spring.application.name=forniture

# Desactiva la caché de Thymeleaf para ver cambios en HTML sin reiniciar el servidor
spring.thymeleaf.cache=false

# Desactiva la caché de archivos estáticos (CSS, JS, imágenes) para que se actualicen al refrescar
spring.web.resources.cache.period=0

# Desactiva el sistema de cacheo interno de recursos estáticos
spring.web.resources.chain.cache=false